site_name: f1a3h's Notebook
site_url: https://note.f1a3h.com
site_description: f1a3h's Notebook

repo_name: f1a3h/mkdocs-notes
repo_url: https://github.com/f1a3h/mkdocs-notes/
edit_uri: tree/master/docs

copyright: Copyright &copy; 2024 <a href="https://github.com/f1a3h" target="_blank" rel="noopener">f1a3h</a>

theme: 
  name: 'material'
  language: 'en'
  icon: 
    logo: fontawesome/solid/fish-fins
    repo: fontawesome/brands/github-alt
    admonition:
      info: fontawesome/solid/anchor
      abstract: fontawesome/solid/list
      tip: fontawesome/solid/lightbulb
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: material/alien
      danger: fontawesome/solid/virus
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/link
  favicon: _assets/img/favicon.png
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
  font:
    text: 
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 10
  - meta
  - abbr
  - nl2br
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - minify
  - search
  - callouts
  - obsidian-bridge
  - include_dir_to_nav

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: ignore
    absolute_links: ignore
    unrecognized_links: ignore

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/f1a3h/
    - icon: fontawesome/solid/rss
      link: https://notes.f1a3h.com/
    - icon: fontawesome/solid/house
      link: https://f1a3h.com/

extra_css:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  # - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://fonts.loli.net/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - https://fonts.loli.net/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap
  - _assets/css/tasklist.css
  - _assets/css/custom.css
  - _assets/css/flink.css
  - _assets/css/font.css
  - _assets/css/admonition.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  # - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  # - https://cdn.tonycrane.cc/utils/katex.min.js
  - _assets/js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

# not_in_nav: 

nav:
  - Home: index.md
  - Computer Science: Computer Science
  - Research: Research
  - Algorithm: Algorithm
  - ACG: ACG
